name: Deploy to Firebase

on:
  push:
    branches: [main]

jobs:
  build_react_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm run install
      - run: npm run build
        env:
          CI: true
          NODE_ENV: production
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only=hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          PROJECT_ID: zingati-erp
